# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/osum4est/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/163.10154.43/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/osum4est/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/163.10154.43/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/osum4est/gdrive/snaike

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/osum4est/gdrive/snaike

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/osum4est/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/163.10154.43/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/osum4est/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/163.10154.43/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/osum4est/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/163.10154.43/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/osum4est/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/163.10154.43/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/osum4est/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/163.10154.43/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/osum4est/gdrive/snaike/CMakeFiles /home/osum4est/gdrive/snaike/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/osum4est/gdrive/snaike/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named snaike

# Build rule for target.
snaike: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 snaike
.PHONY : snaike

# fast build rule for target.
snaike/fast:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/build
.PHONY : snaike/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f lib/glad-0.1.13a0/CMakeFiles/glad.dir/build.make lib/glad-0.1.13a0/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f lib/glfw-3.2.1/CMakeFiles/uninstall.dir/build.make lib/glfw-3.2.1/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f lib/glfw-3.2.1/src/CMakeFiles/glfw.dir/build.make lib/glfw-3.2.1/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/snake/game_object.o: src/snake/game_object.cpp.o

.PHONY : src/snake/game_object.o

# target to build an object file
src/snake/game_object.cpp.o:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/snake/game_object.cpp.o
.PHONY : src/snake/game_object.cpp.o

src/snake/game_object.i: src/snake/game_object.cpp.i

.PHONY : src/snake/game_object.i

# target to preprocess a source file
src/snake/game_object.cpp.i:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/snake/game_object.cpp.i
.PHONY : src/snake/game_object.cpp.i

src/snake/game_object.s: src/snake/game_object.cpp.s

.PHONY : src/snake/game_object.s

# target to generate assembly for a file
src/snake/game_object.cpp.s:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/snake/game_object.cpp.s
.PHONY : src/snake/game_object.cpp.s

src/snake/snake.o: src/snake/snake.cpp.o

.PHONY : src/snake/snake.o

# target to build an object file
src/snake/snake.cpp.o:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/snake/snake.cpp.o
.PHONY : src/snake/snake.cpp.o

src/snake/snake.i: src/snake/snake.cpp.i

.PHONY : src/snake/snake.i

# target to preprocess a source file
src/snake/snake.cpp.i:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/snake/snake.cpp.i
.PHONY : src/snake/snake.cpp.i

src/snake/snake.s: src/snake/snake.cpp.s

.PHONY : src/snake/snake.s

# target to generate assembly for a file
src/snake/snake.cpp.s:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/snake/snake.cpp.s
.PHONY : src/snake/snake.cpp.s

src/snake/snake_game.o: src/snake/snake_game.cpp.o

.PHONY : src/snake/snake_game.o

# target to build an object file
src/snake/snake_game.cpp.o:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/snake/snake_game.cpp.o
.PHONY : src/snake/snake_game.cpp.o

src/snake/snake_game.i: src/snake/snake_game.cpp.i

.PHONY : src/snake/snake_game.i

# target to preprocess a source file
src/snake/snake_game.cpp.i:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/snake/snake_game.cpp.i
.PHONY : src/snake/snake_game.cpp.i

src/snake/snake_game.s: src/snake/snake_game.cpp.s

.PHONY : src/snake/snake_game.s

# target to generate assembly for a file
src/snake/snake_game.cpp.s:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/snake/snake_game.cpp.s
.PHONY : src/snake/snake_game.cpp.s

src/utils/color.o: src/utils/color.cpp.o

.PHONY : src/utils/color.o

# target to build an object file
src/utils/color.cpp.o:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/utils/color.cpp.o
.PHONY : src/utils/color.cpp.o

src/utils/color.i: src/utils/color.cpp.i

.PHONY : src/utils/color.i

# target to preprocess a source file
src/utils/color.cpp.i:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/utils/color.cpp.i
.PHONY : src/utils/color.cpp.i

src/utils/color.s: src/utils/color.cpp.s

.PHONY : src/utils/color.s

# target to generate assembly for a file
src/utils/color.cpp.s:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/utils/color.cpp.s
.PHONY : src/utils/color.cpp.s

src/utils/drawing.o: src/utils/drawing.cpp.o

.PHONY : src/utils/drawing.o

# target to build an object file
src/utils/drawing.cpp.o:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/utils/drawing.cpp.o
.PHONY : src/utils/drawing.cpp.o

src/utils/drawing.i: src/utils/drawing.cpp.i

.PHONY : src/utils/drawing.i

# target to preprocess a source file
src/utils/drawing.cpp.i:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/utils/drawing.cpp.i
.PHONY : src/utils/drawing.cpp.i

src/utils/drawing.s: src/utils/drawing.cpp.s

.PHONY : src/utils/drawing.s

# target to generate assembly for a file
src/utils/drawing.cpp.s:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/utils/drawing.cpp.s
.PHONY : src/utils/drawing.cpp.s

src/utils/input.o: src/utils/input.cpp.o

.PHONY : src/utils/input.o

# target to build an object file
src/utils/input.cpp.o:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/utils/input.cpp.o
.PHONY : src/utils/input.cpp.o

src/utils/input.i: src/utils/input.cpp.i

.PHONY : src/utils/input.i

# target to preprocess a source file
src/utils/input.cpp.i:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/utils/input.cpp.i
.PHONY : src/utils/input.cpp.i

src/utils/input.s: src/utils/input.cpp.s

.PHONY : src/utils/input.s

# target to generate assembly for a file
src/utils/input.cpp.s:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/utils/input.cpp.s
.PHONY : src/utils/input.cpp.s

src/utils/utils.o: src/utils/utils.cpp.o

.PHONY : src/utils/utils.o

# target to build an object file
src/utils/utils.cpp.o:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/utils/utils.cpp.o
.PHONY : src/utils/utils.cpp.o

src/utils/utils.i: src/utils/utils.cpp.i

.PHONY : src/utils/utils.i

# target to preprocess a source file
src/utils/utils.cpp.i:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/utils/utils.cpp.i
.PHONY : src/utils/utils.cpp.i

src/utils/utils.s: src/utils/utils.cpp.s

.PHONY : src/utils/utils.s

# target to generate assembly for a file
src/utils/utils.cpp.s:
	$(MAKE) -f CMakeFiles/snaike.dir/build.make CMakeFiles/snaike.dir/src/utils/utils.cpp.s
.PHONY : src/utils/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... snaike"
	@echo "... glad"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/snake/game_object.o"
	@echo "... src/snake/game_object.i"
	@echo "... src/snake/game_object.s"
	@echo "... src/snake/snake.o"
	@echo "... src/snake/snake.i"
	@echo "... src/snake/snake.s"
	@echo "... src/snake/snake_game.o"
	@echo "... src/snake/snake_game.i"
	@echo "... src/snake/snake_game.s"
	@echo "... src/utils/color.o"
	@echo "... src/utils/color.i"
	@echo "... src/utils/color.s"
	@echo "... src/utils/drawing.o"
	@echo "... src/utils/drawing.i"
	@echo "... src/utils/drawing.s"
	@echo "... src/utils/input.o"
	@echo "... src/utils/input.i"
	@echo "... src/utils/input.s"
	@echo "... src/utils/utils.o"
	@echo "... src/utils/utils.i"
	@echo "... src/utils/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

